- previewhtml-sample/package.json
In package.json, 'main' is set as 'out/src/extension' whereas in tsconfig.json, 'outDir' is set as 'out' which causes runtime errors. 
package.json 'main' parameter is changed to 'out/extension' to prevent those errors.
> Fixed package.json and tsconfig.json conflict

- tree-view-sample/README.md
- tree-view-sample/package.json
- tree-view-sample/vscode.proposed.d.ts
The tree-view sample had a compilation error due a missing brace in `vscode.proposed.d.ts`
This PR
> Fix tree view sample

- lsp-sample/server/src/server.ts
This PR builds on https://github.com/Microsoft/vscode-languageserver-node/pull/324.
I used https://github.com/kieferrm/lsp-dev-setup to setup the experimentation environment.
> Update sample with support for multi-location diagnostics

- lsp-sample/README.md
There is no `.vscode` folder inside the `client` folder that holds some launch configration. The parent directory contains a `.vscode` with a `launch.json` which defines 'Launch Client'.
> Change `client` folder to `lsp-sample`

- webview-sample/README.md
- webview-sample/package.json
When testing #48453. For running `npm run compile` people would not expect a running watch compile.
> Distinguish between watch and compile

- tree-view-sample/USAGE.md
- tree-view-sample/package.json
I have added to the tree-view-sample a change that the example also uses a custom view container
> Added documentation and example of using custom view containers into tree-view-sample

- lsp-sample/.vscode/launch.json
- lsp-sample/server/src/server.ts
A LSP implementation with client + server seems like the ideal use case for a compound launch config (I use it all the time when working on the Haxe extension / language server at least), so it seems like a good idea to include one here.
Also fixed some inconsistent indentation.
> Add a compound launch config to lsp-sample

- lsp-sample/client/package.json
When I use `lsp-sample` as a starting point I sometimes switch my package managers. It would be more robust to directly run `vscode-install` here instead of using a path, because depending on your package manager the path to the bin could be slightly different. 👍
> simplify vscode-install call

- decorator-sample/USAGE.md
I wrote up a `USAGE.md` file to go alongside the decorator sample to describe the Decorator API.
> Adding some usage documentation for the decorator sample

- tree-view-sample/package.json
This fixes a small typo in the `package.json` file where the `Delete Entry` menu item was pointing to a invalid command.
> Fix typo in package.json of tree-view-sample

- tree-view-sample/USAGE.md
Just a little fix on a label in USAGE.md of tree view sample.
> Fix SCM label in contributes views

- decorator-sample/USAGE.md
It was not very clear that I should use the `.setDecorations()` function to remove previously added decorations of a certain decoration type. I updated the note so that others may understand that usage is available and how to do it themselves.
> clarify how to remove decorations for a decoration type from view

- task-provider-sample/package.json
It's built to out/extension.js, so launching the extension currently produces an error. I guess that was caused by this change:
https://github.com/Microsoft/vscode-extension-samples/commit/704f351abdcd509279cef358afa720b1e6c6961f#diff-71ee4bf336efb1f169e66d21bbc6d508
> Fix path to task-provider-sample's main

- configuration-sample/package.json
This pull request fixes the path to the compiled extension.
Curiously the [`./out/extension`](https://github.com/microsoft/vscode-extension-samples/search?q=%22%2Fout%2Fextension%22&unscoped_q=%22%2Fsrc%2Fout%2Fextension%22) path is used far more than the [`./out/src/extension`](https://github.com/microsoft/vscode-extension-samples/search?q="%2Fout%2Fsrc%2Fextension"&unscoped_q="%2Fout%2Fsrc%2Fextension") path.
> Fix extension path

- lsp-sample/.vscodeignore
Not having this will cause the packaged plugin to fail
> Don't remove semver in lsp-example

- helloworld-test-sample/src/test/suite/extension.test.ts
The default location for `extension.ts` is two levels up, not one.
> Fix path to 'extension.ts'

- tree-view-sample/README.md
- tree-view-sample/USAGE.md
There were references to a "viewContainers" contribution point which doesn't exist. This caused a bit of confusion for me. The contribution point is "viewsContainers", as shown here: https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers
Also fixed the formatting of the markdown files:
- Fix mixed whitespace causing rendering issues
- Fix trailing whitespace
- Fix other issues by running through prettier
> Fix reference to viewsContainers contribution point

- lsp-sample/server/src/server.ts
In browsing this file, I noticed the following comment is out of date.
```javascript
// Create a simple text document manager. The text document manager
// supports full document sync only
```
This eb477566c17029d993fdadae7e4f6e30b80f3212 converted this to incremental sync.
> Improve comments

- custom-editor-sample/media/catScratch.css
- custom-editor-sample/media/reset.css
- custom-editor-sample/media/vscode.css
- custom-editor-sample/src/catScratchEditor.ts
- custom-editor-sample/src/pawDrawEditor.ts
- webview-sample/media/reset.css
- webview-sample/media/vscode.css
- webview-sample/src/extension.ts
- webview-view-sample/media/main.css
- webview-view-sample/media/reset.css
- webview-view-sample/media/vscode.css
- webview-view-sample/src/extension.ts
This adds a `reset.css` and `vscode.css` styles to the webview samples so that default elements (text, body, input) are styled to use our color tokens.
> Update webviews to use vscode styles

- webview-sample/package-lock.json
- webview-sample/package.json
Add `@types/node` to `webview-sample` to fix the following compile error:
```
$ npm run compile
> cat-coding@0.0.1 compile /Users/tamura/src/github/vscode-extension-samples/webview-sample
> tsc -p ./
src/extension.ts:28:5 - error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.
28  			console.log(`Got state: ${state}`);
~~~~~~~
Found 1 error.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cat-coding@0.0.1 compile: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cat-coding@0.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! …
```
> Add @types/node to webview-sample

- webview-sample/src/extension.ts
Issue: webviews that get deserialized will use `localResourceRoots` from the deserialized extension version.  This means if the extension gets updated by the marketplace, the deserialized webview will use the wrong localResourceRoot by default, causing the deserialized version to fail to load any resources.
If you set the `panel.webview.options` during the deserialize, you can override it to the new resource roots.
Since this is a sample that others would copy, it seems like good practice to make it clear that extensions which deserialize and limit localResourceRoots should do this. A more involved extension could use this to change their internal build structure but still work across updates.
More context: I put a PR to vscode  (https://github.com/microsoft/vscode/pull/114661) to fix …
> Fix webview sample deserializing after an extension update

- test-provider-sample/src/testProvider.ts
This PR fixes #392
Result:
/assign @connor4312
> fix #392 test-provider-sample: operator is always displayed as '+'

- README.md
The current link to the license file seems broken. This new link should work 😃 
(PS: This samples repository is super helpful—thank you, maintainers!)
> Fix broken link to LICENSE in README.md

- tree-view-sample/package.json
- tree-view-sample/src/testView.ts
- tree-view-sample/vscode.proposed.d.ts
Drag and drop implementation in sample tree view.
I had to modify the getChildren and getParent method since they wouldn't work when reparenting elements.
I implemented the dataProvider and dragAndDropController in the TestView class instead of passing them as functions to simplify the code.
https://user-images.githubusercontent.com/34872381/119911928-3801f880-bf0f-11eb-8505-c3fae098559b.mov
> Implement drag and drop controller

- tree-view-sample/src/jsonOutline.ts
Hello,
I think this call to `parseTree` is unnecessary, because line 23 runs `onActiveEditorChanged()`, which runs `refresh()`, which runs `parseTree`.
Let me know your thoughts, thanks!
> Remove extra parseTree

- i18n-sample/README.md
- i18n-sample/gulpfile.js
- i18n-sample/package-lock.json
- i18n-sample/package.json
- Use `1.55.0` so that the `gulp package` does not fail.
- Fixed typo.
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
Before the changes:
```sh
i18n-sample % gulp package
[09:43:41] Using gulpfile ~/git/vscode-extension-samples/i18n-sample/gulpfile.js
[09:43:41] Starting 'package'...
[09:43:41] Starting 'cleanTask'...
[09:43:41] Finished 'cleanTask' after 11 ms
[09:43:41] Starting 'internalNlsCompileTask'...
[09:43:43] Finished 'internalNlsCompileTask' after 1.8 s
[09:43:43] Starting 'addI18nTask'...
[09:43:43] Finished 'addI18nTask' after 8.69 ms
[09:43:43] Starting 'vscePackageTask'...
[09:43:43] 'vscePackageTask' errored after 5.38 ms
[09:43:43] Error: @types/vscode ^1.34.0 greater than engines.vscode ^1.32.0. Consider upgrade engines.vscode or use an older @types/vscode version
at …
```
> [i18n-sample]: Bumped up `engines.vscode` and `@types/vscode`.

- getting-started-sample/package.json
`startEntries` contribution point is now removed in favour of `file/newFile` menu contribution point, as demonstrated by the hint
> Use new API in 'Getting Started Sample'

- test-provider-sample/.gitignore
- test-provider-sample/package-lock.json
- test-provider-sample/package.json
- Update vscode-dts so that it downloads from the correct place
- Add `enabledApiProposals: [ "testCoverage" ]` to package.json.
> Fix test-provider-sample compilation in VSCode 1.62.3

- lsp-web-extension-sample/client/src/browserClientMain.ts
fixes https://github.com/microsoft/vscode-extension-samples/issues/560
The path to `browserServerMain.js` has target=web query parameter when running on the web. `Uri.toString()`, by default, encodes the `=` character so the resource is not loaded correctly from the unpkg service when published to marketplace
> do not encode the `?target=web` query parameter

- comment-sample/package.json
- extension-terminal-sample/README.md
- extension-terminal-sample/package.json
- extension-terminal-sample/src/extension.ts
Removed `enableProposedApi` from [comment-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/comment-sample) and [extension-terminal-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample) as it is unnecessary and deprecated.
Mentioned in #555
> Remove unused enableProposedApi

- test-provider-sample/.eslintignore
- test-provider-sample/.vscode/settings.json
- test-provider-sample/package-lock.json
- test-provider-sample/package.json
- test-provider-sample/src/extension.ts
- test-provider-sample/src/parser.ts
- test-provider-sample/src/testTree.ts
- Remove now finalized API proposal
- Use `@types/vscode` directly
- Removes references to prettier since the sample doesn't use it
- Indent with tabs to align with other samples
> Clean up test sample

- lsp-embedded-request-forwarding/client/src/extension.ts
> lsp-embedded-request-forwarding: don't encode uri used in map (fix #682)

- authenticationprovider-sample/package-lock.json
- authenticationprovider-sample/package.json
- helloworld-web-sample/package-lock.json
- i18n-sample/package-lock.json
- lsp-web-extension-sample/client/package-lock.json
- lsp-web-extension-sample/package-lock.json
- lsp-web-extension-sample/package.json
- nodefs-provider-sample/package-lock.json
- nodefs-provider-sample/package.json
- notebook-extend-markdown-renderer-sample/package-lock.json
- notebook-renderer-react-sample/package-lock.json
- notebook-renderer-react-sample/package.json
- notebook-renderer-sample/package-lock.json
- notifications-sample/package.json
- package-lock.json
- uri-handler-sample/package-lock.json
- uri-handler-sample/package.json
- webpack-sample/package-lock.json
- welcome-view-content-sample/package-lock.json
- welcome-view-content-sample/package.json
This also removes `mocha` from examples that were not using them since mocha pulls in lots of deps that then have security advisories
> Fix some npm audit issues

- helloworld-web-sample/.vscode/extensions.json
- notebook-extend-markdown-renderer-sample/.vscode/extensions.json
- notebook-renderer-react-sample/.vscode/extensions.json
- notebook-renderer-sample/.vscode/extensions.json
This is a PR to solve issue #714 
After the changes vscode no longer complains about `"... eamodio.tsl-problem-matcher (not found in marketplace)"` when adding certain folders, ( `notebook-*` and `helloworld-web-sample`) to a workspace.
As mentioned in #714 the owner has changed id of his extension on Marketplace to `amodio.tsl-problem-matcher`.
Please read issue #714 for further info and references.
> eamodio.tsl-problem-matcher changed id

- lsp-embedded-language-service/.vscode/launch.json
- lsp-embedded-language-service/client/src/extension.ts
- lsp-embedded-request-forwarding/.vscode/launch.json
- lsp-embedded-request-forwarding/client/src/extension.ts
- lsp-log-streaming-sample/.vscode/launch.json
- lsp-log-streaming-sample/client/src/extension.ts
- lsp-multi-server-sample/.vscode/launch.json
- lsp-multi-server-sample/client/src/extension.ts
- lsp-sample/.vscode/launch.json
- lsp-sample/README.md
- lsp-sample/client/src/extension.ts
- lsp-user-input-sample/.vscode/launch.json
- lsp-user-input-sample/client/src/extension.ts
This is a new (with js-debug) option that makes debugging child processes much easier. Use it for the LSP subprocesses.
Supplants https://github.com/microsoft/vscode-extension-samples/pull/704
> use auto attach children instead of multiple launch configs

- quickinput-sample/src/multiStepInput.ts
As I was trying to use the quickinput-sample I noticed two problems: the `ignoreFocusOut` and `placeholder` were not acting as expected.
Turns out these parameters were not being passed through to the underlying components:
- showInputBox was missing ignoreFocusOut and placeholder
- showQuickPick was missing ignoreFocusOut
Both of those parameters now work.
Create a multi-step sample using those parameters. Observe that the placeholder will render and that moving away from the window and back again keeps the input form open.
https://github.com/microsoft/vscode-discussions/discussions/407#discussioncomment-4680715
> pass missing parameters

- tree-view-sample/.vscode/launch.json
The files are directly under `out`, not under `out/src`
> Fix debugging of tree view sample

- inline-completions/src/extension.ts
We should check the line number before calling `lineAt`
> Fix exception when trying to use negative line numbers

- statusbar-sample/.vscode/launch.json
OutFiles are written to `<workspace>/out/*.js`. Fix this path to be able to debug again.
> Fix outFiles path

- nodefs-provider-sample/src/extension.ts
- source-control-sample/src/afs.ts
- tree-view-sample/src/fileExplorer.ts
The error code is actually [`EACCES`](https://nodejs.org/api/errors.html#common-system-errors), not `EACCESS`.
> Fix EACCES error code name

- LICENSE
- package.json
Trying to ensure that the license info is detected correctly for this repo. Currently, GitHub classifies the license as "other" despite being MIT license. Verified fix using `licensee`
> Fix LICENSE content

- authenticationprovider-sample/src/authProvider.ts
- authenticationprovider-sample/src/extension.ts
1. remove comment about activation event, it doesn't apply anymore as we have implicit activation
2. aligned the ids
3. Fired removed change event which removes the account from the account menu
Fixes https://github.com/microsoft/vscode-extension-samples/issues/991
> Couple AuthProvider Sample fixes

- lsp-embedded-language-service/package.json
it's seem that vscode high version can't work in lsp-embedded-language-service
i find some clues in [official document](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#explaining-the-language-client)
> Note: If your extension is compatible with VS Code versions prior to 1.74.0, you must declare onLanguage:plaintext in the [activationEvents](https://code.visualstudio.com/api/references/activation-events) field of /package.json to tell VS Code to activate the extension as soon as a plain text file is opened (for example a file with the extension .txt):
beacuse lack of activationEvents, it is origin activationEvents config
```
"activationEvents": [],
```
```
"activationEvents": [
"onLanguage:html1"
],
```
I've found that other people have the same …
> fix: lsp-embedded-language-serviceadd  add activationEvents to invoke  client

- test-provider-sample/package.json
`npm i` fails in the `test-provider-sample` because it can't run its postinstall correctly.
cc: @connor4312
> remove postinstall test provider

- chat-sample/.vscodeignore
- chat-sample/package-lock.json
- chat-sample/package.json
out and node_modules should not be ignored by vsce prompt_tsx is a dependency, not a dev_dependency
chatVariableResovler API is not used
> fix sample:

- lsp-embedded-language-service/server/src/languageModelCache.ts
Based on the @type/node version in the project，Parameter type of `clearInterval` is  
`NodeJS.Timeout | string | number | undefined`
When the parameter is `Nodejs.Timer` , The extension can't run
> fix: `lsp-embedded-language-service` cleaninterval args type

- chat-sample/package.json
I do not want runInTerminal to be confused with our built-in agent tool so I put canBeReferencedInPrompt to false.
The other two I put true.
Users should easily see this behaviour since it the main use case of tools is being used in agent mode
> Add canBeReferencedInPrompt property to tools
