- README.md
This PR updates the `README.md` file and improves it by adding image, new title, TitleCasing the headings, and improving the getting started guide.
> 👌 IMPROVE: Readme.md file

- tree-view-sample/USAGE.md
`viewContainers` should be `viewsContainers` this had me confused for an hour when following this file.
> Fix spelling mistake in contribution point.

- webview-sample/.prettierrc.json
- webview-sample/.vscode/extensions.json
- webview-sample/.vscode/launch.json
- webview-sample/.vscode/settings.json
- webview-sample/.vscode/tasks.json
- webview-sample/README.md
- webview-sample/tsconfig.json
- webview-sample/tslint.json
For https://github.com/Microsoft/vscode-extension-samples/issues/110
> Update webview sample for Sample Guideline for #110

- lsp-sample/README.md
> Fix typo in README

- lsp-log-streaming-sample/client/src/test/helper.ts
- lsp-sample/client/src/test/helper.ts
> Fix LSP sample E2E test

- source-control-sample/README.md
- source-control-sample/package.json
- source-control-sample/src/extension.ts
- source-control-sample/src/fiddleRepository.ts
- source-control-sample/src/fiddleSourceControl.ts
- code documentation, clean-up  …
- sourceControlPane argument in the command handlers
- command to open fiddle in the browser
> Clean-up and documentation

- lsp-log-streaming-sample/README.md
> Readme: Syntax highlighting to support comments

- lsp-sample/server/src/server.ts
`textDocument` are missing in some comments.
> Fix invalid comments at lsp-sample

- code-actions-sample/README.md
- code-actions-sample/src/extension.ts
> Fix typos in code-actions-sample

- fsprovider-sample/README.md
Fix typo and resolve markdown lint warning
> Fix typo and resolve markdown lint warning

- task-provider-sample/src/extension.ts
- task-provider-sample/src/rakeTaskProvider.ts
Fixes https://github.com/microsoft/vscode-extension-samples/issues/297
> Remove deprecated API and lint tasks sample

- webview-sample/media/vscode.css
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>
> Fix spelling error

- terminal-sample/README.md
- terminal-sample/package.json
- terminal-sample/src/extension.ts
> Add terminal profile example to terminal-sample

- fsprovider-sample/README.md
show image by fixing wrong link.
> Fix wrong link of image

- semantic-tokens-sample/README.md
> Use jsonc for the sake of beauty

- tree-view-sample/.vscode/launch.json
This is needed for the Test View to show any nodes
> Add --enable-proposed-api to launch.json

- tree-view-sample/package-lock.json
- tree-view-sample/package.json
> fix #400 tree-view-sample: update package.json, package-lock.json

- custom-editor-sample/src/pawDrawEditor.ts
> Fix typo in pawDrawEditor.ts

- lsp-embedded-language-service/README.md
- lsp-embedded-request-forwarding/README.md
I found a typo and fixed it. 😇
> fix: typo, completino -> completion

- contentprovider-sample/src/referencesDocument.ts
> Fix typo in referencesDocument.ts

- nodefs-provider-sample/src/extension.ts
> Fix typo in error message function

- decorator-sample/src/extension.ts
See https://github.com/microsoft/vscode/issues/136241
> Don't delay decorations on editor activation

- lsp-web-extension-sample/.vscode/extensions.json
Fixes #523
Signed-off-by: Vit Gottwald <vit.gottwald@gmail.com>
> Fix extension name

- lsp-sample/README.md
The language in the README was slightly outdated compared to how VS Code UI is described now.
> Update the names of Debug panel and Launch

- .github/SAMPLE_GUIDELINE.md
Updated with some newer requirements and minor fixes
> Update Sample Guideline

- custom-editor-sample/media/pawDraw.js
- custom-editor-sample/package.json
- custom-editor-sample/src/pawDrawEditor.ts
https://github.com/microsoft/vscode/issues/115807
https://github.com/microsoft/vscode/issues/115807#issuecomment-851013383
Sending ArrayBuffers by postMessage has been improved, so it would be nice to reflect this in samples as well.
> Fix postMessage arguments to efficiently send binary data to webview

- .scripts/samples.js
- document-paste/.eslintrc.js
- document-paste/.gitignore
- document-paste/.vscode/extensions.json
- document-paste/.vscode/launch.json
- document-paste/.vscode/settings.json
- document-paste/.vscode/tasks.json
- document-paste/.vscodeignore
- document-paste/README.md
- document-paste/package.json
- document-paste/src/extension.ts
- document-paste/src/vscode.proposed.documentPaste.d.ts
- document-paste/src/vscode.proposed.textEditorDrop.d.ts
- document-paste/tsconfig.json
For https://github.com/microsoft/vscode/issues/30066
> Add paste provider sample

- authenticationprovider-sample/package.json
fixes https://github.com/microsoft/vscode/issues/149810
> add authentication contribution so that is shows up on extension editor and is best practice

- .github/workflows/pr-chat.yml
> Add Pr chat yml

- decorator-sample/USAGE.md
Fix indentation within while loop
> Update USAGE.md indentation

- notebook-extend-markdown-renderer-sample/package.json
- notebook-extend-markdown-renderer-sample/src/emoji.ts
From https://github.com/microsoft/vscode/issues/153873
> Update id of notebook renderer

- test-provider-sample/package.json
Fixes https://github.com/microsoft/vscode-extension-samples/issues/690
> fix: test provider compile error

- lsp-log-streaming-sample/server/src/server.ts
- lsp-web-extension-sample/client/src/browserClientMain.ts
- lsp-web-extension-sample/server/src/browserServerMain.ts
- test-provider-sample/src/extension.ts
> fix: typos

- github-authentication-sample/package.json
ref https://github.com/microsoft/vscode-extension-samples/issues/762
> Use better activation event for github sample

- source-control-sample/src/util.ts
> Fix compile error

- lsp-sample/package.json
Fixes https://github.com/microsoft/vscode-extension-samples/issues/807
> Fix LSP sample activation

- webview-view-sample/README.md
- webview-view-sample/package-lock.json
- webview-view-sample/package.json
This API is no longer proposed. Updates the readme and bumps some packages
> Remove proposed mention in webviewview sample

- .scripts/run-command.js
- helloworld-test-sample/.vscode/launch.json
- helloworld-test-sample/.vscode/settings.json
- helloworld-test-sample/package-lock.json
- helloworld-test-sample/package.json
- helloworld-test-sample/src/test/suite/index.ts
- helloworld-web-sample/package-lock.json
- lsp-sample/package-lock.json
- notebook-renderer-react-sample/package-lock.json
- notebook-renderer-sample/package-lock.json
- product-icon-theme-sample/package-lock.json
- source-control-sample/package-lock.json
- webpack-sample/package-lock.json
- webpack-sample/package.json
- npm audit fix
- Manual fixing a few remaining cases
> Fix npm audit errors

- .scripts/run-command.js
- helloworld-web-sample/package-lock.json
- lsp-web-extension-sample/client/package-lock.json
- lsp-web-extension-sample/package-lock.json
- notebook-extend-markdown-renderer-sample/package-lock.json
- notebook-renderer-react-sample/package-lock.json
- notebook-renderer-sample/package-lock.json
- product-icon-theme-sample/package-lock.json
- source-control-sample/package-lock.json
- webpack-sample/package-lock.json
Also fixes run-command to not stop if it fails on one sample
> Npm Audit fixes

- webview-sample/README.md
This PR updates the README for the Cat Coding extension sample. It adds two new sections:
- A "Commands" section that describes the `Cat Coding: Start cat coding session` and `Cat Coding: Do refactor` commands and their effects.
- A "Messages" section that describes the `alert` message that the webview can send to the extension.
These additions to the README provide more detailed information about the behavior of the Cat Coding extension and how it uses the webview API.
> Updated README with Commands and Messages sections

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/report-issue.yml
This directs users to ask questions on stackoverflow instead of here
> Add basic issue template

- lsp-log-streaming-sample/server/src/server.ts
- lsp-sample/server/src/server.ts
- proposed-api-sample/vscode.d.ts
- telemetry-sample/vscode.d.ts
Update comments to correct small grammatical errors
> Fix incorrect usage of 'an'

- github-authentication-sample/src/credentials.ts
Fixes https://github.com/microsoft/vscode-extension-samples/issues/921
> Await `setOctokit`

- chat-agent-sample/.vscode/tasks.json
> fix hang on F5 by updating problemMatcher

- lsp-web-extension-sample/.vscode/launch.json
- lsp-web-extension-sample/README.md
- lsp-web-extension-sample/webpack.config.js
Fixes https://github.com/microsoft/vscode-extension-samples/issues/645
> Update readme and fix source maps for debugging

- chat-agent-sample/package.json
- chat-agent-sample/src/extension.ts
- chat-agent-sample/src/vscode.proposed.chatAgents2.d.ts
- chat-agent-sample/src/vscode.proposed.languageModels.d.ts
> upadte to latest api

- chat-agent-sample/src/vscode.proposed.chatParticipant.d.ts
Just to make it easier on TPI testers
> Push latest dts

- lsp-web-extension-sample/README.md
For https://github.com/microsoft/vscode-extension-samples/issues/645
> update LSP web extension sample readme

- quickinput-sample/src/basicInput.ts
In this Pull Request, I have replaced the German words in the `showQuickPick` function with English words. This was done to maintain language consistency throughout the code and improve readability for non-German speaking developers.
Changes:
- Replaced German words with their English equivalents in the `showQuickPick` function.
Src:
- quickinput-sample/src/basicInput.ts
> feat(lang): replace German with English in showQuickPick function

- chat-sample/package.json
> "AI" and "Chat" categories are now supported by marketplace

- chat-sample/package.json
We do not want folk adding this to their existing extensions
> chore: remove extension dependency to github copilot chat

- chat-sample/src/extension.ts
fyi @jrieken - in case there is a better way to gracefully handle model not being there
> gracefully handle if model is not there

- chat-sample/package-lock.json
- chat-sample/package.json
> Fix chat-sample postinstall on windows

- chat-sample/package.json
Fixes https://github.com/microsoft/vscode-extension-samples/issues/1050
> Chat sample: update prompt-tsx version

- .github/workflows/triage.yml
This PR adds actions to triage issues that are opened without any assignees.
> Add actions to triage issues

- chat-sample/README.md
- chat-sample/src/extension.ts
> use gpt-4o in sample

- chat-sample/package.json
Refs https://github.com/microsoft/vscode-extension-samples/issues/1072
> require latest vscode version due to https://github.com/microsoft/vscode-extension-samples/issues/1072

- chat-sample/src/extension.ts
> no need to check if error or usage enabled on logger. This is auto-checked

- chat-sample/package.json
- chat-sample/src/extension.ts
> chat sample disambiguation

- semantic-tokens-sample/package.json
This activation event had to be added for the semantic-tokens-sample to work correctly for me.
> Add missing activation event

- chat-sample/src/play.tsx
> Fix `@cat /play` example

- chat-sample/package-lock.json
- chat-sample/package.json
- chat-sample/src/extension.ts
- chat-sample/vscode.d.ts
Temporarily adding `vscode.d.ts` top level until we publish a new types vscode.d.ts 
fyi @roblourens @jrieken 
Will also update docs with this change @ntrogh
> use request.model

- welcome-view-content-sample/package-lock.json
- welcome-view-content-sample/package.json
Now that welcome views support codicon rendering.
> Add call out for icons

- chat-tutorial/package-lock.json
- chat-tutorial/package.json
- chat-tutorial/src/extension.ts
https://github.com/microsoft/vscode-docs/issues/7752
> Update Chat tutorial to use request.model
